# Generated by Django 3.2.20 on 2023-12-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Management',
            fields=[
                ('management_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('phone_no', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'management',
                'managed': False,
            },
        ),
    ]
