# Generated by Django 3.2.20 on 2023-12-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('facilities_id', models.AutoField(primary_key=True, serialize=False)),
                ('seat', models.CharField(max_length=45)),
                ('parking', models.CharField(max_length=45)),
                ('status', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'facilities',
                'managed': False,
            },
        ),
    ]
