# Generated by Django 3.2.20 on 2023-12-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationNews',
            fields=[
                ('news_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('heading', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'notification_news',
                'managed': False,
            },
        ),
    ]
